apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: solr-operator
  namespace: solr3
spec:
  releaseName: solr-operator
  interval: 5m
  timeout: 5m
  install:
    createNamespace: true
    crds: Skip
  upgrade:
    crds: Skip
  chart:
    spec:
      chart: solr-operator
      version: 0.9.1
      sourceRef:
        kind: HelmRepository
        name: apache-solr-chart
        namespace: solr3
