apiVersion: v1
kind: Service
metadata:
  name: solr-admin-lb1
  namespace: solr3
spec:
  type: LoadBalancer  #####
  selector:
    solr-cloud: my-solrcloud-v9
    technology: solr-cloud
  ports:
    - name: solr
      port: 8983
      targetPort: 8983

